version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - creators-net

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - creators-net

  creator-data-producer:
    build:
      context: ./CreatorDataProducer
    container_name: creator-data-producer
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - creators-net

  creators-data-consumer:
    build:
      context: ./CreatorsDataConsumer
    container_name: creators-data-consumer
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - creators-net

  creators-dashboard:
    build:
      context: ./CreatorsDashboard
    container_name: creators-dashboard
    ports:
      - "5173:5173"
    networks:
      - creators-net

  external-tool:
    build:
      context: ./ExternalTool
    container_name: external-tool
    ports:
      - "5000:5000"
    networks:
      - creators-net

networks:
  creators-net:
